import SwiftUI

/// ヒナのドット絵スプライト集。各 Emotion は 1〜3 フレーム持つ (SPEC §11 のテーブル準拠)。
///
/// - グリッドサイズ: **16×16**
/// - 凡例:
///   - `.` 透明
///   - `y` 黄色 (体)、`Y` 影
///   - `B` 黒 (目)、`W` 白 (目ハイライト)
///   - `o` オレンジ (くちばし)、`O` 濃オレンジ (足)
///   - `p` ピンク (頬)、`r` 赤頬 (怒り)、`b` 青ざめ (悲)、`t` 涙、`s` キラキラ
///   - `g` 茶 (拗ねた後ろ姿)、`G` 濃茶
///   - `k` 黒色アウトライン
enum ChickSprites {
    static let palette: [Character: Color] = [
        "y": Color(red: 1.00, green: 0.83, blue: 0.30),
        "Y": Color(red: 0.85, green: 0.65, blue: 0.18),
        "f": Color(red: 1.00, green: 0.78, blue: 0.10),  // flashy / 鮮やか黄 (expectant)
        "m": Color(red: 1.00, green: 0.55, blue: 0.05),  // medium amber (impatient — 橙寄り)
        "a": Color(red: 0.95, green: 0.18, blue: 0.12),  // anger / 真っ赤 (angry — 体ごと激赤)
        "B": Color(red: 0.10, green: 0.10, blue: 0.10),
        "W": Color.white,
        "o": Color(red: 0.95, green: 0.55, blue: 0.18),
        "O": Color(red: 0.78, green: 0.40, blue: 0.10),
        "p": Color(red: 1.00, green: 0.66, blue: 0.75),
        "r": Color(red: 0.55, green: 0.05, blue: 0.05),  // dark red (angry の頬: 体色 a より濃い)
        "b": Color(red: 0.62, green: 0.36, blue: 0.16),  // roasted body / 丸焼き本体 (sad)
        "u": Color(red: 0.78, green: 0.50, blue: 0.22),  // roasted highlight / 焼き色のハイライト
        "n": Color(red: 1.00, green: 0.99, blue: 0.96),  // bone / 骨 (ほぼ純白)
        "N": Color(red: 0.85, green: 0.83, blue: 0.78),  // bone shadow / 骨の影 (薄グレー)
        "t": Color(red: 0.38, green: 0.62, blue: 0.98),
        "s": Color(red: 1.00, green: 0.94, blue: 0.55),
        "g": Color(red: 0.72, green: 0.55, blue: 0.32),
        "G": Color(red: 0.45, green: 0.30, blue: 0.15),
        "k": Color(red: 0.25, green: 0.15, blue: 0.05),
        "q": Color(red: 0.32, green: 0.16, blue: 0.05),  // burnt char (焼き鶏の焦げ目)
    ]

    static func art(_ ascii: String) -> PixelArt {
        let art = PixelArt(ascii, palette: palette)
        #if DEBUG
        // 16×16 厳守 (タイポでズレるとレイアウト崩壊)
        assert(art.height == 16, "ChickSprites: expected 16 rows, got \(art.height)")
        for (i, row) in art.cells.enumerated() {
            assert(row.count == 16, "ChickSprites: row \(i) width=\(row.count) (must be 16)")
        }
        #endif
        return art
    }

    // ─────────────────────────────────────────────────────────────
    // focused — 集中顔。右向き横顔で歩いている
    // ─────────────────────────────────────────────────────────────
    static let focused: [PixelArt] = [
        // 右足が前
        art("""
        ................
        ................
        .....yyyyyyy....
        ....yyyyyyyyy...
        ...yyyyyyyyyyy..
        ..yyyyyyyyyyyy..
        ..yyyyyByyyyyy..
        ..yyyyyByyyyyyo.
        ..yyyyyyyyyyyoo.
        ..yyyyyyyyyyyyo.
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        ......O..OOO....
        ................
        """),
        // 左足が前 (歩行アニメ)
        art("""
        ................
        ................
        .....yyyyyyy....
        ....yyyyyyyyy...
        ...yyyyyyyyyyy..
        ..yyyyyyyyyyyy..
        ..yyyyyByyyyyy..
        ..yyyyyByyyyyyo.
        ..yyyyyyyyyyyoo.
        ..yyyyyyyyyyyyo.
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OOO..O.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // expectant — 期待顔 (目キラキラ + 小ジャンプ)
    // ─────────────────────────────────────────────────────────────
    static let expectant: [PixelArt] = [
        art("""
        ................
        .....ffffff.....
        ....ffffffff....
        ...ffffffffff...
        ..ffffffffffff..
        ..ffBWffffBWff..
        ..ffBBffffBBff..
        ..fffffooffffff.
        ..fffffooffffff.
        ..ffffffffffff..
        ...ffffffffff...
        ....ffffffff....
        .....ffffff.....
        .....OO..OO.....
        ................
        ................
        """),
        // ジャンプ (足が浮く + 1px 上)
        art("""
        ................
        ....ffffffff....
        ...ffffffffff...
        ..ffffffffffff..
        .ffffffffffffff.
        .ffBWffffffBWff.
        .ffBBffffffBBff.
        .ffffffooffffff.
        .ffffffooffffff.
        .ffffffffffffff.
        ..ffffffffffff..
        ...ffffffffff...
        ....ffffffff....
        ................
        .....OO..OO.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // impatient — むっとした顔 (頬ふっくら)。足踏み 3 frame
    // ─────────────────────────────────────────────────────────────
    static let impatient: [PixelArt] = [
        art("""
        ................
        .....mmmmmm.....
        ....mmmmmmmm....
        ...mmmmmmmmmm...
        ..mmmmmmmmmmmm..
        ..mmBBmmmmBBmm..
        ..mmpmmmmmmmpm..
        ..mmmmmoommmmmm.
        ..mmmmmoommmmmm.
        ..mmmmmmmmmmmm..
        ...mmmmmmmmmm...
        ....mmmmmmmm....
        .....mmmmmm.....
        .....OO..OO.....
        ................
        ................
        """),
        art("""
        ................
        .....mmmmmm.....
        ....mmmmmmmm....
        ...mmmmmmmmmm...
        ..mmmmmmmmmmmm..
        ..mmBBmmmmBBmm..
        ..mmpmmmmmmmpm..
        ..mmmmmoommmmmm.
        ..mmmmmoommmmmm.
        ..mmmmmmmmmmmm..
        ...mmmmmmmmmm...
        ....mmmmmmmm....
        .....mmmmmm.....
        .....OO....OO...
        ................
        ................
        """),
        art("""
        ................
        .....mmmmmm.....
        ....mmmmmmmm....
        ...mmmmmmmmmm...
        ..mmmmmmmmmmmm..
        ..mmBBmmmmBBmm..
        ..mmpmmmmmmmpm..
        ..mmmmmoommmmmm.
        ..mmmmmoommmmmm.
        ..mmmmmmmmmmmm..
        ...mmmmmmmmmm...
        ....mmmmmmmm....
        .....mmmmmm.....
        ...OO....OO.....
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // angry — 怒り (目が吊り上がる、頬赤、頭に羽の逆立ち)。プルプル震え
    // ─────────────────────────────────────────────────────────────
    static let angry: [PixelArt] = [
        art("""
        ................
        ......k..k......
        .....aakaakaa...
        ....aaaaaaaa....
        ...aaaaaaaaaa...
        ..aaaaaaaaaaaa..
        ..aaaBaaaaBaaa..
        ..aarBaaaaBaar..
        ..aaaaaooaaaaaa.
        ..aaaaaooaaaaaa.
        ..aaaaaaaaaaaa..
        ...aaaaaaaaaa...
        ....aaaaaaaa....
        .....aaaaaa.....
        .....OO..OO.....
        ................
        """),
        art("""
        ................
        .....k..k.......
        ....aakaakaa....
        ...aaaaaaaa.....
        ..aaaaaaaaaa....
        .aaaaaaaaaaaa...
        .aaaBaaaaBaaa...
        .aarBaaaaBaar...
        .aaaaaooaaaaaa..
        .aaaaaooaaaaaa..
        .aaaaaaaaaaaa...
        ..aaaaaaaaaa....
        ...aaaaaaaa.....
        ....aaaaaa......
        ....OO..OO......
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sad — 悲しみ (うつむき・涙)
    // ─────────────────────────────────────────────────────────────
    // sad — 「放置されすぎて grill された末路」🔥🍗
    // 典型的な丸焼きチキン (🍗 emoji 風): 右肩から骨 1 本 (短く) + ぷっくり楕円の焼き本体
    static let sad: [PixelArt] = [
        art("""
        ................
        ................
        ................
        .............nn.
        .............Nn.
        ............n...
        ...........nq...
        ......qqbbqq....
        .....qbubbubbq..
        ....qbbuubbbubq.
        ....qbbbbbbbbbq.
        ....qbbqbbbbqbq.
        .....qqbbbbbbqq.
        ......qqqqqqqq..
        ................
        ................
        """),
        // 焦げ目位置を少しずらして「ジリジリ」感
        art("""
        ................
        ................
        ................
        .............nn.
        .............Nn.
        ............n...
        ...........nq...
        ......qqbqbqq...
        .....qbbubbubbq.
        ....qbubbqbbbbq.
        ....qbbbbbbqbbq.
        ....qbbbbqbbbbq.
        .....qqbbbbbbqq.
        ......qqqqqqqq..
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // happy — 笑顔 + ✨ 周囲。ぴょんぴょん 3 frame
    // ─────────────────────────────────────────────────────────────
    static let happy: [PixelArt] = [
        art("""
        s..............s
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yyByyyyyyByy..
        ..yypyyooyyypy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        s..............s
        """),
        // jump 1
        art("""
        ..s............s
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        .yyyyyyyyyyyyyy.
        .yyyByyyyyyByyy.
        .yyyByyyyyyByyy.
        .yyypyyooyyypyy.
        .yyyyyyooyyyyyy.
        .yyyyyyyyyyyyyy.
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        ................
        ................
        s..............s
        """),
        // jump 2 (max)
        art("""
        s..............s
        ...yyyyyyyy.....
        ..yyyyyyyyyy....
        .yyyyyyyyyyyy...
        yyyyyyyyyyyyyy..
        yyyByyyyyyByyy..
        yyyByyyyyyByyy..
        yyypyyooyyypyy..
        yyyyyyooyyyyyy..
        yyyyyyyyyyyyyy..
        .yyyyyyyyyyyy...
        ..yyyyyyyyyy....
        ...yyyyyyyy.....
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // lonely — 寂しい、じっとこちらを見上げる
    // ─────────────────────────────────────────────────────────────
    static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yyByyyyyyByy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....OO..OO.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sulking — 拗ね (後ろ向き、トサカだけ見える)
    // ─────────────────────────────────────────────────────────────
    static let sulking: [PixelArt] = [
        art("""
        ................
        ......g.g.......
        .....ggggg......
        ....ggggggg.....
        ...ggggggggg....
        ..gggggggggGG...
        ..ggggggggggG...
        ..ggggggggggG...
        ..ggggggggggG...
        ..gggggggggGG...
        ...gggggggGG....
        ....ggggGGG.....
        .....gggGG......
        .....OO.OO......
        ................
        ................
        """),
    ]

    // MARK: - Lookup
    static func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .focused:   return focused
        case .expectant: return expectant
        case .impatient: return impatient
        case .angry:     return angry
        case .sad:       return sad
        case .happy:     return happy
        case .lonely:    return lonely
        case .sulking:   return sulking
        }
    }

    /// SPEC §5 のフレームスピード方針: 200-500ms。表情ごとに速度変える。
    static func frameDurationMs(for emotion: Emotion) -> Int {
        switch emotion {
        case .focused:                    return 320   // 歩行リズム
        case .lonely, .sulking:           return 600   // ゆったり / 静止
        case .expectant:                  return 350
        case .impatient:                  return 200   // 足踏みパタパタ
        case .angry:                      return 100   // プルプル震え
        case .sad:                        return 900   // 丸焼き化したのでゆったり (ジリジリ焼ける感)
        case .happy:                      return 200   // ぴょんぴょん
        }
    }
}

