import SwiftUI

/// ヒナのドット絵スプライト集。各 Emotion は 1〜3 フレーム持つ (SPEC §11 のテーブル準拠)。
///
/// - グリッドサイズ: **16×16**
/// - 凡例:
///   - `.` 透明
///   - `y` 黄色 (体)、`Y` 影
///   - `B` 黒 (目)、`W` 白 (目ハイライト)
///   - `o` オレンジ (くちばし)、`O` 濃オレンジ (足)
///   - `p` ピンク (頬)、`r` 赤頬 (怒り)、`b` 青ざめ (悲)、`t` 涙、`s` キラキラ
///   - `g` 茶 (拗ねた後ろ姿)、`G` 濃茶
///   - `k` 黒色アウトライン
enum ChickSprites {
    static let palette: [Character: Color] = [
        "y": Color(red: 1.00, green: 0.83, blue: 0.30),
        "Y": Color(red: 0.85, green: 0.65, blue: 0.18),
        "f": Color(red: 1.00, green: 0.78, blue: 0.10),  // fresh / 元気な黄 (working/focused 歩行用)
        "B": Color(red: 0.10, green: 0.10, blue: 0.10),
        "W": Color.white,
        "o": Color(red: 0.95, green: 0.55, blue: 0.18),
        "O": Color(red: 0.78, green: 0.40, blue: 0.10),
        "p": Color(red: 1.00, green: 0.66, blue: 0.75),
        "r": Color(red: 0.92, green: 0.30, blue: 0.30),
        "b": Color(red: 0.62, green: 0.80, blue: 1.00),
        "t": Color(red: 0.38, green: 0.62, blue: 0.98),
        "s": Color(red: 1.00, green: 0.94, blue: 0.55),
        "g": Color(red: 0.72, green: 0.55, blue: 0.32),
        "G": Color(red: 0.45, green: 0.30, blue: 0.15),
        "k": Color(red: 0.25, green: 0.15, blue: 0.05),
    ]

    static func art(_ ascii: String) -> PixelArt {
        let art = PixelArt(ascii, palette: palette)
        #if DEBUG
        // 16×16 厳守 (タイポでズレるとレイアウト崩壊)
        assert(art.height == 16, "ChickSprites: expected 16 rows, got \(art.height)")
        for (i, row) in art.cells.enumerated() {
            assert(row.count == 16, "ChickSprites: row \(i) width=\(row.count) (must be 16)")
        }
        #endif
        return art
    }

    // ─────────────────────────────────────────────────────────────
    // focused — 集中顔。右向き横顔で歩いている
    // ─────────────────────────────────────────────────────────────
    static let focused: [PixelArt] = [
        // 右足が前
        art("""
        ................
        ................
        .....fffffff....
        ....fffffffff...
        ...fffffffffff..
        ..ffffffffffff..
        ..fffffBffffff..
        ..fffffBffffffo.
        ..fffffffffffoo.
        ..ffffffffffffo.
        ..ffffffffffff..
        ...ffffffffff...
        ....ffffffff....
        .....ffffff.....
        ......O..OOO....
        ................
        """),
        // 左足が前 (歩行アニメ)
        art("""
        ................
        ................
        .....fffffff....
        ....fffffffff...
        ...fffffffffff..
        ..ffffffffffff..
        ..fffffBffffff..
        ..fffffBffffffo.
        ..fffffffffffoo.
        ..ffffffffffffo.
        ..ffffffffffff..
        ...ffffffffff...
        ....ffffffff....
        .....ffffff.....
        .....OOO..O.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // expectant — 期待顔 (目キラキラ + 小ジャンプ)
    // ─────────────────────────────────────────────────────────────
    static let expectant: [PixelArt] = [
        art("""
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyBWyyyyBWyy..
        ..yyBByyyyBByy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        ................
        ................
        """),
        // ジャンプ (足が浮く + 1px 上)
        art("""
        ................
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        .yyyyyyyyyyyyyy.
        .yyBWyyyyyyBWyy.
        .yyBByyyyyyBByy.
        .yyyyyyooyyyyyy.
        .yyyyyyooyyyyyy.
        .yyyyyyyyyyyyyy.
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        ................
        .....OO..OO.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // impatient — むっとした顔 (頬ふっくら)。足踏み 3 frame
    // ─────────────────────────────────────────────────────────────
    static let impatient: [PixelArt] = [
        art("""
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyBByyyyBByy..
        ..yypyyyyyyypy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        ................
        ................
        """),
        art("""
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyBByyyyBByy..
        ..yypyyyyyyypy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO....OO...
        ................
        ................
        """),
        art("""
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyBByyyyBByy..
        ..yypyyyyyyypy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        ...OO....OO.....
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // angry — 怒り (目が吊り上がる、頬赤、頭に羽の逆立ち)。プルプル震え
    // ─────────────────────────────────────────────────────────────
    static let angry: [PixelArt] = [
        art("""
        ................
        ......k..k......
        .....yykykyy....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyyByyyyByyy..
        ..yyrByyyyByyr..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        ................
        """),
        art("""
        ................
        .....k..k.......
        ....yykykyy.....
        ...yyyyyyyy.....
        ..yyyyyyyyyy....
        .yyyyyyyyyyyy...
        .yyyByyyyByyy...
        .yyrByyyyByyr...
        .yyyyyooyyyyy...
        .yyyyyooyyyyy...
        .yyyyyyyyyyyy...
        ..yyyyyyyyyy....
        ...yyyyyyyy.....
        ....yyyyyy......
        ....OO..OO......
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sad — 悲しみ (うつむき・涙)
    // ─────────────────────────────────────────────────────────────
    static let sad: [PixelArt] = [
        art("""
        ................
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yytyyyyyyyty..
        ..yytyyyooyyty..
        ..yyyyyyooyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        ................
        """),
        art("""
        ................
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yytyyyyyyyty..
        ..yytyyyooyyty..
        ..yyttyyooyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // happy — 笑顔 + ✨ 周囲。ぴょんぴょん 3 frame
    // ─────────────────────────────────────────────────────────────
    static let happy: [PixelArt] = [
        art("""
        s..............s
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yyByyyyyyByy..
        ..yypyyooyyypy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....yyyyyy.....
        .....OO..OO.....
        s..............s
        """),
        // jump 1
        art("""
        ..s............s
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        .yyyyyyyyyyyyyy.
        .yyyByyyyyyByyy.
        .yyyByyyyyyByyy.
        .yyypyyooyyypyy.
        .yyyyyyooyyyyyy.
        .yyyyyyyyyyyyyy.
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        ................
        ................
        s..............s
        """),
        // jump 2 (max)
        art("""
        s..............s
        ...yyyyyyyy.....
        ..yyyyyyyyyy....
        .yyyyyyyyyyyy...
        yyyyyyyyyyyyyy..
        yyyByyyyyyByyy..
        yyyByyyyyyByyy..
        yyypyyooyyypyy..
        yyyyyyooyyyyyy..
        yyyyyyyyyyyyyy..
        .yyyyyyyyyyyy...
        ..yyyyyyyyyy....
        ...yyyyyyyy.....
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // lonely — 寂しい、じっとこちらを見上げる
    // ─────────────────────────────────────────────────────────────
    static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ................
        .....yyyyyy.....
        ....yyyyyyyy....
        ...yyyyyyyyyy...
        ..yyyyyyyyyyyy..
        ..yyByyyyyyByy..
        ..yyByyyyyyByy..
        ..yyyyyooyyyyy..
        ..yyyyyooyyyyy..
        ..yyyyyyyyyyyy..
        ...yyyyyyyyyy...
        ....yyyyyyyy....
        .....OO..OO.....
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sulking — 拗ね (後ろ向き、トサカだけ見える)
    // ─────────────────────────────────────────────────────────────
    static let sulking: [PixelArt] = [
        art("""
        ................
        ......g.g.......
        .....ggggg......
        ....ggggggg.....
        ...ggggggggg....
        ..gggggggggGG...
        ..ggggggggggG...
        ..ggggggggggG...
        ..ggggggggggG...
        ..gggggggggGG...
        ...gggggggGG....
        ....ggggGGG.....
        .....gggGG......
        .....OO.OO......
        ................
        ................
        """),
    ]

    // MARK: - Lookup
    static func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .focused:   return focused
        case .expectant: return expectant
        case .impatient: return impatient
        case .angry:     return angry
        case .sad:       return sad
        case .happy:     return happy
        case .lonely:    return lonely
        case .sulking:   return sulking
        }
    }

    /// SPEC §5 のフレームスピード方針: 200-500ms。表情ごとに速度変える。
    static func frameDurationMs(for emotion: Emotion) -> Int {
        switch emotion {
        case .focused:                    return 320   // 歩行リズム
        case .lonely, .sulking:           return 600   // ゆったり / 静止
        case .expectant:                  return 350
        case .impatient:                  return 200   // 足踏みパタパタ
        case .angry:                      return 100   // プルプル震え
        case .sad:                        return 500
        case .happy:                      return 200   // ぴょんぴょん
        }
    }
}

