import SwiftUI

/// マスコット種 — ねこ (cat)。`mascot_model = "cat"` で選択する。
///
/// ドット絵は 16×16 グリッド。右向きの横顔。とがった耳としなる尻尾が特徴。
/// - 凡例:
///   - `.` 透明
///   - `o` 橙 (体)、`O` 濃橙 (耳・尻尾・脚・アウトライン)、`l` クリーム (口元)
///   - `e` 緑 (目)、`W` 白 (目ハイライト)、`n` 桃 (鼻)
///   - `k` 逆立つ毛 (angry)、`t` 涙、`s` キラキラ
struct CatModel: MascotModel {
    let id = "cat"
    let displayName = "ねこ"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "にゃ?"
        case .impatient:                    return "にゃっにゃっ"
        case .angry:                        return "フーッ!"
        case .sad:                          return "に...ゃ..."
        case .happy:                        return "にゃん♪"
        case .lonely:                       return "にゃあ..."
        }
    }

    // MARK: - Sprites

    private static let palette: [Character: Color] = [
        "o": Color(red: 0.95, green: 0.62, blue: 0.28),  // body
        "O": Color(red: 0.72, green: 0.42, blue: 0.16),  // ear / tail / leg / outline
        "l": Color(red: 0.99, green: 0.93, blue: 0.80),  // cream muzzle
        "e": Color(red: 0.32, green: 0.66, blue: 0.34),  // green eye
        "W": Color.white,                                 // eye highlight
        "n": Color(red: 0.95, green: 0.55, blue: 0.60),  // nose
        "k": Color(red: 0.50, green: 0.28, blue: 0.10),  // angry bristled fur
        "t": Color(red: 0.40, green: 0.64, blue: 0.98),  // tear
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // focused — 右向きに歩く (脚を交互に)
    private static let focused: [PixelArt] = [
        art("""
        ................
        ................
        .........O.O....
        ........OoOoO...
        .O......OooooO..
        .OO.....oooooo..
        ..Oo...ooeooooo.
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ...O.O....O.O...
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        .........O.O....
        ........OoOoO...
        .O......OooooO..
        .OO.....oooooo..
        ..Oo...ooeooooo.
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ..O.O......O.O..
        ..O.O......O.O..
        ................
        ................
        ................
        """),
    ]

    // expectant — 耳ぴん、目キラキラ、小ジャンプ
    private static let expectant: [PixelArt] = [
        art("""
        ......s.........
        .........O.O....
        ........OoOoO...
        .......OoooooO..
        ......OooooooO..
        .O.....ooooooo..
        .OO...ooeWoooo..
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ...O.O....O.O...
        ...............s
        ................
        ................
        """),
        art("""
        ......s.........
        .........O.O....
        ........OoOoO...
        .......OoooooO..
        ......OooooooO..
        .O.....ooooooo..
        .OO...ooeWoooo..
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ....OO....OO....
        ................
        ...............s
        ................
        ................
        """),
    ]

    // impatient — 目を細め、尻尾をぴくぴく振る
    private static let impatient: [PixelArt] = [
        art("""
        ................
        ................
        .........O.O....
        ........OoOoO...
        ........OooooO..
        ........oooooo..
        ..Oo...ooOooooo.
        .Oooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ...O.O....O.O...
        ................
        ................
        ................
        """),
        art("""
        ....O...........
        ...OoO...O.O....
        ...OoO..OoOoO...
        ...Oo...OooooO..
        ...Oo...oooooo..
        ...oo..ooOooooo.
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ...O.O....O.O...
        ................
        ................
        ................
        ................
        """),
    ]

    // angry — 背を弓なりに反らし、毛を逆立て、脚を突っ張る。プルプル震え
    private static let angry: [PixelArt] = [
        art("""
        ................
        ....k.kk.kk.k...
        ...OOkOOkOOkOO..
        ..OOOOOOOOOOOO..
        .OOooooooooooO..
        .O.ooooeooooooO.
        ...ooooooooonnO.
        ...ooooooooolln.
        ...ooooooooooo..
        ...oo.oooo.ooo..
        ...O...OO...O...
        ................
        ................
        ................
        ................
        ................
        """),
        art("""
        ................
        .....k.kk.kk.k..
        ....OOkOOkOOkOO.
        ...OOOOOOOOOOOO.
        ..OOooooooooooO.
        ..O.ooooeooooooO
        ....ooooooooonnO
        ....ooooooooolln
        ....ooooooooooo.
        ....oo.oooo.ooo.
        ....O...OO...O..
        ................
        ................
        ................
        ................
        ................
        """),
    ]

    // sad — 耳をたらし、うなだれる。涙
    private static let sad: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        .........ooooO..
        ........oooooooO
        .O.....ooeoooooO
        .OO...oooooooonn
        ..oooooooooollnt
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ................
        ............t...
        ................
        ................
        """),
        art("""
        ................
        ................
        ................
        ................
        .........ooooO..
        ........oooooooO
        .O.....ooeoooooO
        .OO...oooooooonn
        ..ooooooooooolln
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ................
        ................
        ..........t.....
        ................
        """),
    ]

    // happy — 尻尾を立てて飛び跳ねる + ✨
    private static let happy: [PixelArt] = [
        art("""
        s..............s
        .........O.O....
        ........OoOoO...
        .O.....OoooooO..
        .OO....OoooooO..
        ..Oo...oooooo...
        ..ooooooeWooooo.
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...O.O....O.O...
        ...O.O....O.O...
        ................
        ................
        s..............s
        """),
        art("""
        s..............s
        .........O.O....
        ........OoOoO...
        .O.....OoooooO..
        .OO....OoooooO..
        ..Oo...oooooo...
        ..ooooooeWooooo.
        ..ooooooooooonn.
        ..oooooooooolln.
        ..ooooooooooooo.
        ...O.O....O.O...
        ................
        ................
        ................
        ................
        s..............s
        """),
    ]

    // lonely — お座りしてこちらを見上げる
    private static let lonely: [PixelArt] = [
        art("""
        ................
        .........O.O....
        ........OoOoO...
        .......OoooooO..
        ......oooooooo..
        .....oooeWooooo.
        ..O..oooooooonn.
        ..Oo.ooooooolln.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ..ooooooooooooo.
        ...OO......OO...
        ................
        ................
        ................
        """),
    ]

    // sulking — 拗ね (顔を伏せて丸くなる)
    private static let sulking: [PixelArt] = [
        art("""
        ................
        ................
        ....O.....O.....
        ...OoO...OoO....
        ...OooOOOOooO...
        ..OoooooooooooO.
        ..OooooooooooO..
        ..OoooooooooO...
        .OooooooooooooO.
        .OoooooooooooooO
        ..OooooooooooO..
        ...OOOOOOOOOO...
        ................
        ................
        ................
        ................
        """),
    ]
}
