import SwiftUI

/// マスコット種 — いぬ (dog)。`mascot_model = "dog"` で選択する。
///
/// ドット絵は 16×16 グリッド。右向きの横顔 (chick の focused と同じ向き)。
/// - 凡例:
///   - `.` 透明
///   - `b` 茶 (体)、`d` 焦茶 (耳・脚・尻尾・アウトライン)、`l` クリーム (口元・腹)
///   - `e` 黒 (目)、`W` 白 (目ハイライト)、`n` 黒 (鼻)
///   - `t` 桃 (舌)、`s` キラキラ
struct DogModel: MascotModel {
    let id = "dog"
    let displayName = "いぬ"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "わん?"
        case .impatient:                    return "わんわんっ"
        case .angry:                        return "ガルルッ!"
        case .sad:                          return "くぅ...ん..."
        case .happy:                        return "わんっ♪"
        case .lonely:                       return "くぅん..."
        }
    }

    // MARK: - Sprites

    private static let palette: [Character: Color] = [
        "b": Color(red: 0.80, green: 0.58, blue: 0.32),  // body
        "d": Color(red: 0.52, green: 0.34, blue: 0.16),  // ear / leg / tail / outline
        "l": Color(red: 0.96, green: 0.90, blue: 0.78),  // cream muzzle / belly
        "e": Color(red: 0.12, green: 0.10, blue: 0.08),  // eye
        "W": Color.white,                                 // eye highlight
        "n": Color(red: 0.16, green: 0.11, blue: 0.08),  // nose
        "t": Color(red: 0.95, green: 0.45, blue: 0.50),  // tongue
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // focused — 右向きに歩く (脚を交互に)
    private static let focused: [PixelArt] = [
        art("""
        ................
        ................
        ..........d.....
        .........dd.....
        ........dddbbb..
        ...b...bbbbbbbb.
        ..bbb..bbebbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...b.b....b.b...
        ...d.d....d.d...
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        ..........d.....
        .........dd.....
        ........dddbbb..
        ...b...bbbbbbbb.
        ..bbb..bbebbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ..b.b......b.b..
        ..d.d......d.d..
        ................
        ................
        ................
        """),
    ]

    // expectant — 両耳ぴんと立て、目キラキラ、小ジャンプ
    private static let expectant: [PixelArt] = [
        art("""
        ......s.........
        ........d.d.....
        ........ddd.....
        .......ddddd....
        ......dddbbbb...
        ..b...bbbbbbbb..
        .bbb..bbeWbbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...b.b....b.b...
        ...d.d....d.d...
        ...............s
        ................
        ................
        """),
        art("""
        ......s.........
        ........d.d.....
        ........ddd.....
        .......ddddd....
        ......dddbbbb...
        ..b...bbbbbbbb..
        .bbb..bbeWbbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...dd......dd...
        ................
        ...............s
        ................
        ................
        """),
    ]

    // impatient — 尻尾を下げて前足をタッタッと踏む
    private static let impatient: [PixelArt] = [
        art("""
        ................
        ................
        ..........d.....
        .........dd.....
        ........dddbbb..
        .b.....bbbbbbbb.
        .bb....bbebbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...b.b.....bb...
        ...d.d.....dd...
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        ..........d.....
        .........dd.....
        ........dddbbb..
        .b.....bbbbbbbb.
        .bb....bbebbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...b.b....b..b..
        ...d.d....d..d..
        ................
        ................
        ................
        """),
    ]

    // angry — 耳を伏せ、牙をむいて吠える。プルプル震え
    private static let angry: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ...ddd..........
        ..ddbbbbbbbb....
        ...bbbbbbbbbb...
        ..bbbbbbebbbbb..
        ..bbbbbbbbbbbbn.
        ..bbbbbbbbWWWnn.
        ..bbbbbbbbWWbll.
        ..bbbbbbbbbbbb..
        ...d.d....d.d...
        ................
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        ................
        ..ddd...........
        ...ddbbbbbbbb...
        ..bbbbbbbbbbbb..
        ..bbbbbbebbbbb..
        ..bbbbbbbbbbbbn.
        ..bbbbbbbWWWWnn.
        ..bbbbbbbWWWbll.
        ..bbbbbbbbbbbb..
        ..d.d......d.d..
        ................
        ................
        ................
        ................
        """),
    ]

    // sad — 耳をたらし、うなだれて尻尾も下がる。涙
    private static let sad: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        .........bbbb...
        ........bbbbbbbd
        .b.....bbebbbbdd
        .bb...bbbbbbbnnd
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...d.d....d.d...
        ................
        .............t..
        ................
        ................
        """),
        art("""
        ................
        ................
        ................
        ................
        .........bbbb...
        ........bbbbbbbd
        .b.....bbebbbbdd
        .bb...bbbbbbbnnd
        ..bbbbbbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ...d.d....d.d...
        ................
        ................
        ............t...
        ................
        """),
    ]

    // happy — 尻尾を振り、舌を出して飛び跳ねる + ✨
    private static let happy: [PixelArt] = [
        art("""
        s..............s
        ................
        ......d...d.....
        ......dd.dd.....
        ........dddbbb..
        ...b...bbbbbbbb.
        ..bbb..bbeWbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnnt
        ..bbbbbbbbbbbllt
        ..bbbbbbbbbbbb..
        ...b.b....b.b...
        ...d.d....d.d...
        ................
        ................
        s..............s
        """),
        art("""
        s..............s
        ......d...d.....
        ......dd.dd.....
        ........dddbbb..
        ...b...bbbbbbbb.
        ..bbb..bbeWbbbb.
        ..bbbbbbbbbbbnn.
        ..bbbbbbbbbblnnt
        ..bbbbbbbbbbbllt
        ..bbbbbbbbbbbb..
        ...b.b....b.b...
        ...d.d....d.d...
        ................
        ................
        ................
        s..............s
        """),
    ]

    // lonely — お座りしてこちらを見上げる
    private static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ..........d.....
        .........dd.....
        ........dddbbb..
        .......bbbbbbbb.
        ......bbbeWbbbb.
        ..b...bbbbbbbnn.
        ..bb..bbbbbblnn.
        ..bbbbbbbbbbbll.
        ..bbbbbbbbbbbb..
        ..bbbbbbbbbbbbb.
        ...ddd.....dd...
        ................
        ................
        ................
        """),
    ]

    // sulking — 拗ね (顔を背けて丸まり、尻尾を下げる)
    private static let sulking: [PixelArt] = [
        art("""
        ................
        ................
        .....dd.........
        ....dddd........
        ...ddbbbbb......
        ..bbbbbbbbbb....
        ..ebbbbbbbbbbb..
        ..bbbbbbbbbbbbb.
        ..bbbbbbbbbbbbb.
        ...bbbbbbbbbbbd.
        ...bbbbbbbbbbdd.
        ...d.d....dd....
        ...d.d....d.....
        ................
        ................
        ................
        """),
    ]
}
