import SwiftUI

/// マスコット種 — おばけ (ghost)。`mascot_model = "ghost"` で選択する。
///
/// ドット絵は 16×16 グリッド。正面向きで宙に浮く。歩行アニメは無く、ふわふわ漂う。
/// - 凡例:
///   - `.` 透明
///   - `w` 体 (淡い白)、`W` ハイライト (純白)、`G` 影 (灰紫)
///   - `B` 目・口 (暗い空洞)
///   - `a` 興奮色 (angry)、`A` 濃い興奮色
///   - `d` くすんだ青 (sad)、`t` 涙、`s` キラキラ
struct GhostModel: MascotModel {
    let id = "ghost"
    let displayName = "おばけ"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "ぼう?"
        case .impatient:                    return "ぼうぼうっ"
        case .angry:                        return "ボォーッ!"
        case .sad:                          return "ぼ...う..."
        case .happy:                        return "ぼうっ♪"
        case .lonely:                       return "ぼう..."
        }
    }

    // MARK: - Sprites

    private static let palette: [Character: Color] = [
        "w": Color(red: 0.92, green: 0.92, blue: 0.98),  // body
        "W": Color.white,                                 // highlight
        "G": Color(red: 0.72, green: 0.72, blue: 0.82),  // shade
        "B": Color(red: 0.20, green: 0.18, blue: 0.30),  // eye / mouth (hollow)
        "a": Color(red: 0.95, green: 0.74, blue: 0.74),  // angry body
        "A": Color(red: 0.66, green: 0.30, blue: 0.30),  // angry dark (mouth)
        "d": Color(red: 0.66, green: 0.72, blue: 0.82),  // sad dull
        "t": Color(red: 0.40, green: 0.64, blue: 0.98),  // tear
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // focused — ふわふわ左右に漂う
    private static let focused: [PixelArt] = [
        art("""
        ................
        .....WWWW.......
        ....wwwwwww.....
        ...wwwwwwwww....
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wwBBwwwBBww...
        ..wwBBwwwBBww...
        ..wwwwwwwwwww...
        ..wwwwBBBwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..ww.www.www....
        ..w...w...w.....
        ................
        """),
        art("""
        ................
        ......WWWW......
        .....wwwwwww....
        ....wwwwwwwww...
        ...wwwwwwwwwww..
        ...wwwwwwwwwww..
        ...wwBBwwwBBww..
        ...wwBBwwwBBww..
        ...wwwwwwwwwww..
        ...wwwwBBBwwww..
        ...wwwwwwwwwww..
        ...wwwwwwwwwww..
        ...wwwwwwwwwww..
        ...www.www.ww...
        ....w...w...w...
        ................
        """),
    ]

    // expectant — 目キラキラ、ふわっと浮き上がる
    private static let expectant: [PixelArt] = [
        art("""
        ......s.........
        .....WWWW.......
        ....wwwwwww.....
        ...wwwwwwwww....
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wWBwwwwWBww...
        ..wwBBwwwBBww...
        ..wwwwwwwwwww...
        ..wwwwwBBwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..ww.www.www....
        ..w...w...w....s
        ................
        """),
        art("""
        ......s.........
        ................
        .....WWWW.......
        ....wwwwwww.....
        ...wwwwwwwww....
        ..wwwwwwwwwww...
        ..wWBwwwwWBww...
        ..wwBBwwwBBww...
        ..wwwwwwwwwww...
        ..wwwwwBBwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..ww.www.www....
        ..w...w...w.....
        ...............s
        ................
        """),
    ]

    // impatient — 目を細め、左右にぶるぶる揺れる
    private static let impatient: [PixelArt] = [
        art("""
        ................
        ....WWWW........
        ...wwwwwww......
        ..wwwwwwwww.....
        .wwwwwwwwwww....
        .wwwwwwwwwww....
        .wwGGwwwGGww....
        .wwwwwwwwwww....
        .wwwwwwwwwww....
        .wwwwBBBwwww....
        .wwwwwwwwwww....
        .wwwwwwwwwww....
        .wwwwwwwwwww....
        .ww.www.www.....
        .w...w...w......
        ................
        """),
        art("""
        ................
        ........WWWW....
        .......wwwwwww..
        ......wwwwwwwww.
        .....wwwwwwwwwww
        .....wwwwwwwwwww
        .....wwGGwwwGGww
        .....wwwwwwwwwww
        .....wwwwwwwwwww
        .....wwwwBBBwwww
        .....wwwwwwwwwww
        .....wwwwwwwwwww
        .....wwwwwwwwwww
        .....ww.www.www.
        .....w...w...w..
        ................
        """),
    ]

    // angry — 赤く染まり、吊り目で威嚇。プルプル震え
    private static let angry: [PixelArt] = [
        art("""
        ................
        .....aaaa.......
        ....aaaaaaa.....
        ...aaaaaaaaa....
        ..aaaaaaaaaaa...
        ..aaaaaaaaaaa...
        ..aaBaaaaaBaa...
        ..aaaBaaaBaaa...
        ..aaaaaaaaaaa...
        ..aaaAAAAAaaa...
        ..aaaaaaaaaaa...
        ..aaaaaaaaaaa...
        ..aaaaaaaaaaa...
        ..aa.aaa.aaa....
        ...a..a...a.....
        ................
        """),
        art("""
        ................
        ......aaaa......
        .....aaaaaaa....
        ....aaaaaaaaa...
        ...aaaaaaaaaaa..
        ...aaaaaaaaaaa..
        ...aaBaaaaaBaa..
        ...aaaBaaaBaaa..
        ...aaaaaaaaaaa..
        ...aaaAAAAAaaa..
        ...aaaaaaaaaaa..
        ...aaaaaaaaaaa..
        ...aaaaaaaaaaa..
        ...aaa.aaa.aa...
        ....a...a...a...
        ................
        """),
    ]

    // sad — 青ざめて下に垂れ下がり、涙がこぼれる
    private static let sad: [PixelArt] = [
        art("""
        ................
        ................
        .....dddd.......
        ....ddddddd.....
        ...ddddddddd....
        ...ddddddddd....
        ...ddBddBddd....
        ...ddBddBddd....
        ...ddddddddd....
        ...dddddddddt...
        ...ddddddddd....
        ...ddddddddd....
        ...ddddddddd....
        ...dd.ddd.dd....
        ....d..d...d....
        ................
        """),
        art("""
        ................
        ................
        .....dddd.......
        ....ddddddd.....
        ...ddddddddd....
        ...ddddddddd....
        ...ddBddBddd....
        ...ddBddBddd....
        ...ddddddddd....
        ...ddddddddd....
        ...ddddddddd....
        ...ddddddddd....
        ...ddddddddd....
        ...dd.ddd.dd....
        ....d..d...d....
        .............t..
        """),
    ]

    // happy — にっこり笑って弾むように浮かぶ + ✨
    private static let happy: [PixelArt] = [
        art("""
        s..............s
        .....WWWW.......
        ....wwwwwww.....
        ...wwwwwwwww....
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wwWBwwwBWww...
        ..wwwwwwwwwww...
        ..wwwBwwwwwBw...
        ..wwwBBBBBBww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..ww.www.www....
        ..w...w...w.....
        s..............s
        """),
        art("""
        s..............s
        ................
        .....WWWW.......
        ....wwwwwww.....
        ...wwwwwwwww....
        ..wwwwwwwwwww...
        ..wwWBwwwBWww...
        ..wwwwwwwwwww...
        ..wwwBwwwwwBw...
        ..wwwBBBBBBww...
        ..wwwwwwwwwww...
        ..wwwwwwwwwww...
        ..ww.www.www....
        ..w...w...w.....
        ................
        s..............s
        """),
    ]

    // lonely — 小さくしぼんでこちらを見つめる
    private static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ......GGGG......
        .....wwwwww.....
        ....wwwwwwww....
        ....wwwwwwww....
        ....wBBwwBBw....
        ....wBBwwBBw....
        ....wwwwwwww....
        ....wwwwwwww....
        ....wwwwwwww....
        ....ww.ww.ww....
        .....w..w..w....
        ................
        ................
        """),
    ]

    // sulking — 拗ね (色あせて目を閉じる)
    private static let sulking: [PixelArt] = [
        art("""
        ................
        ................
        .....GGGG.......
        ....GGGGGGG.....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GGwwGGwwG....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GGGGGGGGG....
        ...GG.GGG.GG....
        ....G..G...G....
        ................
        """),
    ]
}
