import SwiftUI

/// マスコット種 — とかげ (lizard)。`mascot_model = "lizard"` で選択する試作モデル。
///
/// ドット絵は 16×16 グリッド。右向きの横顔 (chick の focused と同じ向き)。
/// - 凡例:
///   - `.` 透明
///   - `g` 緑 (体)、`G` 濃緑 (影・脚・斑点・アウトライン)、`l` 黄緑 (腹)
///   - `B` 黒 (目)、`W` 白 (目ハイライト)
///   - `r` 赤 (舌)、`s` キラキラ
///   - `a` 興奮色 (angry の体)、`A` 濃い興奮色、`k` 背びれの棘 (angry)
///   - `d` くすんだ淡色 (sad)、`D` くすんだ濃色、`t` 涙
struct LizardModel: MascotModel {
    let id = "lizard"
    let displayName = "とかげ"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    /// とかげは舌をちろちろさせて鳴く。thinking / focused / sulking は無音。
    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "ちろ?"
        case .impatient:                    return "ちろちろっ"
        case .angry:                        return "シャーッ!"
        case .sad:                          return "ち...ろ..."
        case .happy:                        return "ちろっ♪"
        case .lonely:                       return "ちろ..."
        }
    }

    // ─────────────────────────────────────────────────────────────
    // MARK: - Sprites
    // ─────────────────────────────────────────────────────────────

    private static let palette: [Character: Color] = [
        "g": Color(red: 0.46, green: 0.73, blue: 0.33),  // leaf green / 体
        "G": Color(red: 0.27, green: 0.46, blue: 0.20),  // dark green / 影・脚・斑点
        "l": Color(red: 0.74, green: 0.87, blue: 0.55),  // light belly / 腹
        "B": Color(red: 0.10, green: 0.10, blue: 0.10),  // eye
        "W": Color.white,                                 // eye highlight
        "r": Color(red: 0.93, green: 0.32, blue: 0.40),  // tongue / 舌
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
        "a": Color(red: 0.66, green: 0.62, blue: 0.16),  // angry body / 興奮色
        "A": Color(red: 0.42, green: 0.37, blue: 0.10),  // angry dark
        "k": Color(red: 0.16, green: 0.24, blue: 0.10),  // spike / 背びれの棘
        "d": Color(red: 0.58, green: 0.63, blue: 0.54),  // sad dull / くすみ淡
        "D": Color(red: 0.42, green: 0.46, blue: 0.39),  // sad dull dark
        "t": Color(red: 0.40, green: 0.64, blue: 0.98),  // tear
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // ─────────────────────────────────────────────────────────────
    // focused — 右向きに歩く。脚を交互に動かし、舌をちろっと出す
    // ─────────────────────────────────────────────────────────────
    private static let focused: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggBggg.
        ....ggggGgggggg.
        ..gggggggggggggr
        ggggggggggggggg.
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G.G....
        ................
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggBggg.
        ....ggggGgggggg.
        ..gggggggggggggg
        ggggggggggggggg.
        ..gggggGgggggg..
        ....lllllllll...
        ....G.G...G.G...
        ................
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // expectant — 目キラキラ + 舌を二股に出す + 小ジャンプ
    // ─────────────────────────────────────────────────────────────
    private static let expectant: [PixelArt] = [
        art("""
        ......s.........
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggBWgg.
        ....ggggGgggggg.
        ..gggggggggggggr
        gggggggggggggggr
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G.G....
        ................
        ...............s
        ................
        ................
        """),
        // ジャンプ (1px 上 + 脚を縮める)
        art("""
        ......s.........
        ................
        ...........gggg.
        ..........ggggg.
        .........ggBWgg.
        ....ggggGgggggg.
        ..gggggggggggggr
        gggggggggggggggr
        ..gggggGgggggg..
        ....lllllllll...
        ....G..G.G..G...
        ................
        ................
        ...............s
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // impatient — 目を細め、前足をタッタッと踏み鳴らす
    // ─────────────────────────────────────────────────────────────
    private static let impatient: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggGGgg.
        ....ggggGgggggg.
        ..gggggggggggggr
        ggggggggggggggg.
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G....GG....
        ................
        ................
        ................
        ................
        """),
        art("""
        ................
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggGGgg.
        ....ggggGgggggg.
        ..gggggggggggggg
        ggggggggggggggg.
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G..G...
        ................
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // angry — 体を膨らませ、背びれを逆立て、シャーッと威嚇。プルプル震え
    // ─────────────────────────────────────────────────────────────
    private static let angry: [PixelArt] = [
        art("""
        ................
        .......k.k.k....
        ......kakakak...
        ......aaaaaaaa..
        .....aaaaaaaaa..
        ....aaaaaaBaaa..
        ...aaaaAaaaaaaar
        .aaaaaaaaaaaaaar
        aaaaaaaaaaaaaa..
        ..aaaaaAaaaaa...
        ...AAAAAAAAA....
        ..A.A....A.A....
        ................
        ................
        ................
        ................
        """),
        art("""
        ................
        ........k.k.k...
        .......kakakak..
        .......aaaaaaaa.
        ......aaaaaaaaa.
        .....aaaaaaBaaa.
        ....aaaaAaaaaaar
        ..aaaaaaaaaaaaar
        .aaaaaaaaaaaaaa.
        ...aaaaaAaaaaa..
        ....AAAAAAAAA...
        ...A.A....A.A...
        ................
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sad — 放置されすぎて干からびた末路。ぐったり伏せて涙がぽろり
    // ─────────────────────────────────────────────────────────────
    private static let sad: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..........dddd..
        .........dBdddd.
        ....ddddddDddddt
        ..dddddddddddddd
        .ddddddddddddDd.
        ...dddddddddd...
        ...d.d....d.d...
        ................
        ................
        ................
        """),
        // 涙が落ちる
        art("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..........dddd..
        .........dBdddd.
        ....dddddddddddd
        ..dddddddddddddd
        .ddddddddddddDd.
        ...dddddddddd...
        ...d.d....d.d...
        ..............t.
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // happy — 舌を出してご機嫌に飛び跳ねる + ✨ 周囲
    // ─────────────────────────────────────────────────────────────
    private static let happy: [PixelArt] = [
        art("""
        s..............s
        ................
        ................
        ...........gggg.
        ..........ggggg.
        .........ggBWgg.
        ....ggggGgggggg.
        ..gggggggggggggr
        gggggggggggggggr
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G.G....
        ................
        ................
        ................
        s..............s
        """),
        // jump
        art("""
        s..............s
        ...........gggg.
        ..........ggggg.
        .........ggBWgg.
        ....ggggGgggggg.
        ..gggggggggggggr
        gggggggggggggggr
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G.G....
        ................
        ................
        ................
        ................
        ................
        s..............s
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // lonely — 顔を上げてじっとこちらを見上げる
    // ─────────────────────────────────────────────────────────────
    private static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ...........gggg.
        ..........ggBgg.
        .........gggggg.
        ....ggggGgggggg.
        ..gggggggggggggg
        ggggggggggggggg.
        ..gggggGgggggg..
        ....lllllllll...
        ...G.G...G.G....
        ................
        ................
        ................
        ................
        """),
    ]

    // ─────────────────────────────────────────────────────────────
    // sulking — 拗ね (背を丸めて尻尾を巻き上げ、顔を伏せる)
    // ─────────────────────────────────────────────────────────────
    private static let sulking: [PixelArt] = [
        art("""
        ................
        ................
        .........GG.....
        ........GggG....
        .......GgggG....
        ....GGGGgggG....
        ..GGgggggggGG...
        .GgggggggggggG..
        .GgggggggggggG..
        .GgggggggggggG..
        ..GgggggggggG...
        ...GG.G..G.GG...
        ................
        ................
        ................
        ................
        """),
    ]
}
