import SwiftUI

/// マスコット種 — ロボット (robot)。`mascot_model = "robot"` で選択する。
///
/// ドット絵は 16×16 グリッド。正面向きの直立体型で、四角い頭・胴を縦に大きく取る。
/// dog / cat のような横向きは占有率が低く視認性に欠けたため、縦に占有率の高い種へ寄せた設計。
/// - 凡例:
///   - `.` 透明
///   - `r` 体 (鋼色)、`R` 体の影・アウトライン、`B` 暗部 (アンテナ柱・関節・足・パネル)
///   - `e` 目 LED (シアン)、`W` 白 (目ハイライト)、`y` アンテナ灯
///   - `a` 興奮色 LED (angry)
///   - `d` くすんだ LED (sad)、`t` 冷却液の涙、`s` キラキラ
struct RobotModel: MascotModel {
    let id = "robot"
    let displayName = "ロボット"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "ピッ?"
        case .impatient:                    return "ピピッ ピピッ"
        case .angry:                        return "ビーーッ!"
        case .sad:                          return "ピ...ー..."
        case .happy:                        return "ピロリ♪"
        case .lonely:                       return "ピ..."
        }
    }

    // MARK: - Sprites

    private static let palette: [Character: Color] = [
        "r": Color(red: 0.62, green: 0.68, blue: 0.74),  // body metal
        "R": Color(red: 0.40, green: 0.45, blue: 0.52),  // body shadow / outline
        "B": Color(red: 0.14, green: 0.16, blue: 0.20),  // dark (antenna stalk / joints / feet / panel)
        "e": Color(red: 0.35, green: 0.85, blue: 0.95),  // eye LED (cyan)
        "W": Color.white,                                 // eye highlight
        "y": Color(red: 1.00, green: 0.80, blue: 0.20),  // antenna light
        "a": Color(red: 0.95, green: 0.25, blue: 0.20),  // angry LED
        "d": Color(red: 0.40, green: 0.50, blue: 0.62),  // sad dim LED
        "t": Color(red: 0.40, green: 0.64, blue: 0.98),  // coolant tear
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // focused — 直立して足を交互に踏み出す歩行アニメ
    private static let focused: [PixelArt] = [
        art("""
        .......B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReeRReeR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        """),
        art("""
        .......B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReeRReeR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ...BB......BB...
        ................
        """),
    ]

    // expectant — 目 LED を大きく灯し、きらきらが弾ける
    private static let expectant: [PixelArt] = [
        art("""
        .......B......s.
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReeeeeeR....
        ....ReeWWeeR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        .s..BB....BB....
        ................
        """),
        art("""
        .s.....B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReeeeeeR....
        ....ReeWWeeR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB..s.
        ................
        """),
    ]

    // impatient — 目を細め、足をパタパタ踏み鳴らす 3 frame
    private static let impatient: [PixelArt] = [
        art("""
        .......B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RrrrrrrR....
        ....RBBRRBBR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        """),
        art("""
        .......B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RrrrrrrR....
        ....RBBRRBBR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB......BB..
        ................
        """),
        art("""
        .......B........
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RrrrrrrR....
        ....RBBRRBBR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrBBBBrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ..BB......BB....
        ................
        """),
    ]

    // angry — アンテナ灯と目 LED が真っ赤に。プルプル震え
    private static let angry: [PixelArt] = [
        art("""
        .......a........
        .......a........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RaaRRaaR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrraaaarrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        """),
        art("""
        ........a.......
        ........a.......
        ......RRRRRR....
        .....RrrrrrrR...
        .....RaaRRaaR...
        .....RrrrrrrR...
        .....RRRRRRRR...
        ......R....R....
        ....RRRRRRRRRR..
        ....RrrrrrrrrR..
        ....RrraaaarrR..
        ....RrrrrrrrrR..
        ....RRRRRRRRRR..
        .....RR....RR...
        .....BB....BB...
        ................
        """),
    ]

    // sad — アンテナがうなだれ、目 LED が暗み、冷却液の涙がこぼれる
    private static let sad: [PixelArt] = [
        art("""
        ......B.........
        .....B..........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RddRRddR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        .t.RrrrrrrrrR...
        ...RrrddddrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        """),
        art("""
        ......B.........
        .....B..........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....RddRRddR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RrrddddrrR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        .t..RR....RR....
        ....BB....BB....
        ................
        """),
    ]

    // happy — 目 LED を弾ませ、アンテナにきらきら + ✨。ぴょんと跳ねる
    private static let happy: [PixelArt] = [
        art("""
        s......B.......s
        .......y........
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReWeeWeR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RreeeeeerR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        s..............s
        """),
        art("""
        s......B.......s
        .....RRRRRR.....
        ....RrrrrrrR....
        ....ReWeeWeR....
        ....RrrrrrrR....
        ....RRRRRRRR....
        .....R....R.....
        ...RRRRRRRRRR...
        ...RrrrrrrrrR...
        ...RreeeeeerR...
        ...RrrrrrrrrR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        s..............s
        """),
    ]

    // lonely — 小さくうずくまり、目 LED をこちらに向け見上げる
    private static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        .......B........
        .......y........
        .....RRRRRR.....
        .....RrrrrR.....
        .....ReeeeR.....
        .....ReeeeR.....
        .....RrrrrR.....
        .....RRRRRR.....
        ......R..R......
        .....RR..RR.....
        .....BB..BB.....
        ................
        ................
        ................
        """),
    ]

    // sulking — 拗ね (背を向け、頭を垂れて電源を落としたように色をくすませる)
    private static let sulking: [PixelArt] = [
        art("""
        ................
        .......B........
        .....RRRRRR.....
        ....RRRRRRRR....
        ....RRRRRRRR....
        ....RRRRRRRR....
        ....RRRRRRRR....
        .....RRRRRR.....
        ...RRRRRRRRRR...
        ...RRRRRRRRRR...
        ...RRRRRRRRRR...
        ...RRRRRRRRRR...
        ...RRRRRRRRRR...
        ....RR....RR....
        ....BB....BB....
        ................
        """),
    ]
}
