import SwiftUI

/// マスコット種 — スライム (slime)。`mascot_model = "slime"` で選択する。
///
/// ドット絵は 16×16 グリッド。正面向きの丸い体で、表情は squash/stretch と色で出す。
/// - 凡例:
///   - `.` 透明
///   - `g` 緑 (体)、`G` 濃緑 (底の影・アウトライン)、`h` ハイライト (上面の照り)
///   - `B` 黒 (目)、`W` 白 (目ハイライト)
///   - `a` 興奮色 (angry)、`A` 濃い興奮色、`k` 逆立つ棘 (angry)
///   - `d` くすんだ青灰 (sad)、`D` 濃いくすみ、`t` 涙、`s` キラキラ
struct SlimeModel: MascotModel {
    let id = "slime"
    let displayName = "スライム"

    func frames(for emotion: Emotion) -> [PixelArt] {
        switch emotion {
        case .thinking:  return Self.focused
        case .focused:   return Self.focused
        case .expectant: return Self.expectant
        case .impatient: return Self.impatient
        case .angry:     return Self.angry
        case .sad:       return Self.sad
        case .happy:     return Self.happy
        case .lonely:    return Self.lonely
        case .sulking:   return Self.sulking
        }
    }

    func cry(for emotion: Emotion) -> String? {
        switch emotion {
        case .thinking, .focused, .sulking: return nil
        case .expectant:                    return "ぷる?"
        case .impatient:                    return "ぷるぷるっ"
        case .angry:                        return "ぶるるッ!"
        case .sad:                          return "ぷ...る..."
        case .happy:                        return "ぷるんっ♪"
        case .lonely:                       return "ぷる..."
        }
    }

    // MARK: - Sprites

    private static let palette: [Character: Color] = [
        "g": Color(red: 0.40, green: 0.78, blue: 0.55),  // body
        "G": Color(red: 0.24, green: 0.56, blue: 0.38),  // base shadow / outline
        "h": Color(red: 0.70, green: 0.95, blue: 0.78),  // top highlight
        "B": Color(red: 0.10, green: 0.10, blue: 0.10),  // eye
        "W": Color.white,                                 // eye highlight
        "a": Color(red: 0.86, green: 0.40, blue: 0.30),  // angry body
        "A": Color(red: 0.60, green: 0.22, blue: 0.16),  // angry dark
        "k": Color(red: 0.30, green: 0.10, blue: 0.08),  // angry spike
        "d": Color(red: 0.52, green: 0.62, blue: 0.66),  // sad dull
        "D": Color(red: 0.36, green: 0.44, blue: 0.48),  // sad dull dark
        "t": Color(red: 0.40, green: 0.64, blue: 0.98),  // tear
        "s": Color(red: 1.00, green: 0.95, blue: 0.60),  // sparkle
    ]

    private static func art(_ ascii: String) -> PixelArt {
        mascotPixelArt(ascii, palette: palette)
    }

    // focused — ぷるぷる揺れる (縦長 ↔ 横平の squash/stretch)
    private static let focused: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..ggBWgggBWggg..
        ..ggBBgggBBggg..
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        """),
        art("""
        ................
        ................
        ................
        ................
        ......hhhh......
        ....gghhhhgg....
        ..gggggggggggg..
        .gggggggggggggg.
        .ggBWgggggBWggg.
        .ggBBgggggBBggg.
        gggggggggggggggg
        gggggggggggggggg
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        """),
    ]

    // expectant — 目キラキラ + ぴょこんと伸び上がる
    private static let expectant: [PixelArt] = [
        art("""
        ......s.........
        ................
        ................
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..gWBgggggWBg...
        ..gBBgggggBBg...
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ...............s
        """),
        art("""
        ......s.........
        ................
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..gWBgggggWBg...
        ..gBBgggggBBg...
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        ...............s
        """),
    ]

    // impatient — 目を細めてイライラ小刻みに揺れる
    private static let impatient: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..gGGgggggGGg...
        ..gggggggggggg..
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        """),
        art("""
        ................
        ................
        ................
        ................
        ......hhhh......
        ....gghhhhgg....
        ..gggggggggggg..
        .gggggggggggggg.
        .ggGGgggggGGgg..
        .gggggggggggggg.
        gggggggggggggggg
        gggggggggggggggg
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        """),
    ]

    // angry — 真っ赤に染まり、てっぺんに棘を逆立てる。プルプル震え
    private static let angry: [PixelArt] = [
        art("""
        ................
        ....k.k..k.k....
        ....kakaakak....
        ....aaaaaaaa....
        ...aaaaaaaaaa...
        ..aaaaaaaaaaaa..
        ..aaaaaaaaaaaa..
        ..aaaaaaaaaaaa..
        ..aaBaaaaaaBaa..
        ..aaaaaaaaaaaa..
        .aaaaaaaaaaaaaa.
        .aaaaaaaaaaaaaa.
        .aaaaaaaaaaaaaa.
        ..AaaaaaaaaaaA..
        ...AAAAAAAAAA...
        ................
        """),
        art("""
        ................
        .....k.k..k.k...
        .....kakaakak...
        .....aaaaaaaa...
        ....aaaaaaaaaa..
        ...aaaaaaaaaaaa.
        ...aaaaaaaaaaaa.
        ...aaaaaaaaaaaa.
        ...aaBaaaaaaBaa.
        ...aaaaaaaaaaaa.
        ..aaaaaaaaaaaaaa
        ..aaaaaaaaaaaaaa
        ..aaaaaaaaaaaaaa
        ...AaaaaaaaaaaA.
        ....AAAAAAAAAA..
        ................
        """),
    ]

    // sad — どろりと溶けて平たく広がり、涙がこぼれる
    private static let sad: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        ................
        ................
        ......dddd......
        ....dddddddd....
        ...ddBddddBdd...
        ..dddddddddddd..
        .dddddddddddddd.
        dddddddddddddddd
        dddddddddddddddt
        .DDDddddddddDDD.
        ..DDDDDDDDDDDD..
        ................
        """),
        art("""
        ................
        ................
        ................
        ................
        ................
        ................
        ......dddd......
        ....dddddddd....
        ...ddBddddBdd...
        ..dddddddddddd..
        .dddddddddddddd.
        dddddddddddddddd
        dddddddddddddddd
        .DDDddddddddDDD.
        ..DDDDDDDDDDDD..
        .............t..
        """),
    ]

    // happy — ご機嫌に大きく弾む + ✨
    private static let happy: [PixelArt] = [
        art("""
        s..............s
        ................
        ................
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..gBWgggggBWg...
        ..gggggggggggg..
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        s..............s
        """),
        art("""
        s..............s
        ......hhhh......
        .....gghhgg.....
        ....gggggggg....
        ...gggggggggg...
        ..gggggggggggg..
        ..gBWgggggBWg...
        ..gggggggggggg..
        .gggggggggggggg.
        .gggggggggggggg.
        .gggggggggggggg.
        ..GggggggggggG..
        ...GGGGGGGGGG...
        ................
        ................
        s..............s
        """),
    ]

    // lonely — 小さくしぼんで見上げる
    private static let lonely: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        ................
        .......hh.......
        ......gggg......
        .....gggggg.....
        ....gBWggBWg....
        ....gggggggg....
        ...gggggggggg...
        ...gggggggggg...
        ...gggggggggg...
        ....GgggggggG...
        ....GGGGGGGG....
        ................
        """),
    ]

    // sulking — 拗ね (顔を伏せてぺたんと潰れる)
    private static let sulking: [PixelArt] = [
        art("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....GGGGGGGG....
        ..GGggggggggGG..
        .GgggggggggggG..
        .gggggggggggggg.
        .gggggggggggggg.
        .GggggggggggggG.
        ..GGGGGGGGGGGG..
        ................
        """),
    ]
}
